// <auto-generated />
using Lab0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab0.Migrations
{
    [DbContext(typeof(AddDbContext))]
    [Migration("20251123010802_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Lab0.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfPublishing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Adam Mickiewicz",
                            ISBN = "1111111111",
                            PageNumber = 0,
                            Title = "Pan Tadeusz",
                            YearOfPublishing = 1834
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bolesław Prus",
                            ISBN = "2222222222",
                            PageNumber = 0,
                            Title = "Lalka",
                            YearOfPublishing = 1890
                        },
                        new
                        {
                            Id = 3,
                            Author = "K.K. Martin",
                            ISBN = "3333333333",
                            PageNumber = 0,
                            Title = "Professional C# 9",
                            YearOfPublishing = 1990
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
